export const UPDATE_FOO = 'UPDATE_FOO';
export const INCREMENT_TIME = 'INCREMENT_TIME';
export const RESET_TIME = 'RESET_TIME';
export const SET_CURR_TAB = 'SET_CURR_TAB';
export const SET_CURR_TAB_PREV_TIME = 'SET_CURR_TAB_PREV_TIME';